# Generated by Django 5.2.4 on 2025-07-21 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_emailverificationtoken_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0)),
                ('unique_views', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('avg_time_on_page', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('top_referral_sources', models.JSONField(default=dict)),
                ('geographic_distribution', models.JSONField(default=dict)),
                ('skill_match_distribution', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Job Analytics',
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=40)),
                ('view_duration', models.IntegerField(default=0)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='applications_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='remote_work_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='application_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (3-5 years)'), ('senior', 'Senior Level (6-10 years)'), ('lead', 'Lead Level (10+ years)'), ('executive', 'Executive Level')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_max',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_min',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='skills_required',
            field=models.TextField(db_index=True, help_text='Comma-separated skills'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['is_active', 'created_at'], name='matcher_job_is_acti_4ce893_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['location', 'is_active'], name='matcher_job_locatio_ff8c63_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['job_type', 'experience_level'], name='matcher_job_job_typ_ddbb06_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['salary_min', 'salary_max'], name='matcher_job_salary__079703_idx'),
        ),
        migrations.AddField(
            model_name='jobanalytics',
            name='job_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='matcher.jobpost'),
        ),
        migrations.AddField(
            model_name='jobview',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_views', to='matcher.jobpost'),
        ),
        migrations.AddField(
            model_name='jobview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['job_post', 'viewed_at'], name='matcher_job_job_pos_cb1d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['viewer', 'viewed_at'], name='matcher_job_viewer__3f432a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['ip_address', 'viewed_at'], name='matcher_job_ip_addr_e21fbc_idx'),
        ),
    ]
