# Generated by Django 5.2.4 on 2025-07-22 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_jobanalytics_jobview_jobpost_applications_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_posted_enabled', models.BooleanField(default=True)),
                ('job_posted_delivery', models.CharField(choices=[('websocket', 'Real-time WebSocket'), ('email', 'Email'), ('both', 'Both WebSocket and Email'), ('none', 'Disabled')], default='websocket', max_length=20)),
                ('application_received_enabled', models.BooleanField(default=True)),
                ('application_received_delivery', models.CharField(choices=[('websocket', 'Real-time WebSocket'), ('email', 'Email'), ('both', 'Both WebSocket and Email'), ('none', 'Disabled')], default='websocket', max_length=20)),
                ('application_status_changed_enabled', models.BooleanField(default=True)),
                ('application_status_changed_delivery', models.CharField(choices=[('websocket', 'Real-time WebSocket'), ('email', 'Email'), ('both', 'Both WebSocket and Email'), ('none', 'Disabled')], default='both', max_length=20)),
                ('match_score_calculated_enabled', models.BooleanField(default=True)),
                ('match_score_calculated_delivery', models.CharField(choices=[('websocket', 'Real-time WebSocket'), ('email', 'Email'), ('both', 'Both WebSocket and Email'), ('none', 'Disabled')], default='websocket', max_length=20)),
                ('interview_scheduled_enabled', models.BooleanField(default=True)),
                ('interview_scheduled_delivery', models.CharField(choices=[('websocket', 'Real-time WebSocket'), ('email', 'Email'), ('both', 'Both WebSocket and Email'), ('none', 'Disabled')], default='both', max_length=20)),
                ('system_message_enabled', models.BooleanField(default=True)),
                ('system_message_delivery', models.CharField(choices=[('websocket', 'Real-time WebSocket'), ('email', 'Email'), ('both', 'Both WebSocket and Email'), ('none', 'Disabled')], default='websocket', max_length=20)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default='22:00')),
                ('quiet_hours_end', models.TimeField(default='08:00')),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('job_posted', 'Job Posted'), ('application_received', 'Application Received'), ('application_status_changed', 'Application Status Changed'), ('match_score_calculated', 'Match Score Calculated'), ('interview_scheduled', 'Interview Scheduled'), ('system_message', 'System Message'), ('reminder', 'Reminder')], max_length=30)),
                ('delivery_channel', models.CharField(choices=[('websocket', 'WebSocket'), ('email', 'Email'), ('push', 'Push Notification')], max_length=20)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('email_subject_template', models.CharField(blank=True, max_length=255)),
                ('email_html_template', models.TextField(blank=True)),
                ('available_variables', models.JSONField(default=dict, help_text='JSON object documenting available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['template_type', 'delivery_channel'], name='matcher_not_templat_750dbd_idx'), models.Index(fields=['is_active', 'is_default'], name='matcher_not_is_acti_407ed0_idx')],
                'unique_together': {('template_type', 'delivery_channel', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('job_posted', 'Job Posted'), ('application_received', 'Application Received'), ('application_status_changed', 'Application Status Changed'), ('match_score_calculated', 'Match Score Calculated'), ('interview_scheduled', 'Interview Scheduled'), ('system_message', 'System Message'), ('reminder', 'Reminder')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matcher.application')),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matcher.jobpost')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='matcher_not_recipie_91c434_idx'), models.Index(fields=['notification_type', 'created_at'], name='matcher_not_notific_58b714_idx'), models.Index(fields=['priority', 'is_read'], name='matcher_not_priorit_a9aac2_idx'), models.Index(fields=['expires_at'], name='matcher_not_expires_50dcc0_idx')],
            },
        ),
    ]
