# Generated by Django 5.2.4 on 2025-07-29 03:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0004_notificationpreference_notificationtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(choices=[('direct', 'Direct Message'), ('job_inquiry', 'Job Inquiry'), ('interview', 'Interview Discussion'), ('support', 'Support Ticket')], default='direct', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matcher.application')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matcher.jobpost')),
            ],
            options={
                'db_table': 'matcher_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('file', 'File Attachment'), ('image', 'Image'), ('system', 'System Message')], default='text', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_attachments/')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='matcher.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matcher_message',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PopularSearchTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('jobs', 'Job Search'), ('candidates', 'Candidate Search')], max_length=20)),
                ('term', models.CharField(db_index=True, max_length=255)),
                ('search_count', models.IntegerField(default=1)),
                ('click_through_rate', models.FloatField(default=0.0)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-search_count', '-last_searched'],
                'indexes': [models.Index(fields=['search_type', 'search_count'], name='matcher_pop_search__452717_idx'), models.Index(fields=['term', 'search_type'], name='matcher_pop_term_59ce8e_idx')],
                'unique_together': {('search_type', 'term')},
            },
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('professional', 'Professional'), ('creative', 'Creative'), ('modern', 'Modern'), ('classic', 'Classic'), ('academic', 'Academic'), ('technical', 'Technical')], default='professional', max_length=20)),
                ('template_data', models.JSONField(default=dict, help_text='Template structure and styling data')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='resume_templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matcher_resumetemplate',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('search_type', models.CharField(choices=[('jobs', 'Job Search'), ('candidates', 'Candidate Search')], max_length=20)),
                ('query', models.TextField(blank=True)),
                ('filters', models.JSONField(default=dict)),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('alert_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_type', models.CharField(choices=[('jobs', 'Job Search'), ('candidates', 'Candidate Search')], max_length=20)),
                ('query', models.TextField(blank=True)),
                ('filters_applied', models.JSONField(default=dict)),
                ('results_count', models.IntegerField(default=0)),
                ('clicked_results', models.JSONField(default=list)),
                ('search_duration', models.FloatField(default=0.0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=40)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchSuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('jobs', 'Job Search'), ('candidates', 'Candidate Search')], max_length=20)),
                ('suggestion_type', models.CharField(choices=[('query', 'Query Suggestion'), ('skill', 'Skill Suggestion'), ('location', 'Location Suggestion'), ('company', 'Company Suggestion'), ('title', 'Job Title Suggestion')], max_length=20)),
                ('text', models.CharField(db_index=True, max_length=255)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-popularity_score', 'text'],
                'indexes': [models.Index(fields=['search_type', 'suggestion_type', 'is_active'], name='matcher_sea_search__439afd_idx'), models.Index(fields=['text', 'search_type'], name='matcher_sea_text_ee2cad_idx'), models.Index(fields=['popularity_score', 'is_active'], name='matcher_sea_popular_37a28a_idx')],
                'unique_together': {('search_type', 'suggestion_type', 'text')},
            },
        ),
        migrations.CreateModel(
            name='UserSearchPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_job_filters', models.JSONField(default=dict)),
                ('default_candidate_filters', models.JSONField(default=dict)),
                ('results_per_page', models.IntegerField(default=20)),
                ('sort_preference', models.CharField(choices=[('relevance', 'Relevance'), ('date', 'Date Posted'), ('salary', 'Salary'), ('popularity', 'Popularity')], default='relevance', max_length=20)),
                ('email_alerts_enabled', models.BooleanField(default=False)),
                ('alert_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('recent_job_searches', models.JSONField(default=list)),
                ('recent_candidate_searches', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', 'is_active'], name='matcher_con_convers_3f4ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='matcher_con_updated_3c9b77_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at'], name='matcher_mes_convers_fd2c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'sent_at'], name='matcher_mes_sender__029e04_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='matcher_mes_is_read_b1e6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='resumetemplate',
            index=models.Index(fields=['category', 'is_active'], name='matcher_res_categor_a302fa_idx'),
        ),
        migrations.AddIndex(
            model_name='resumetemplate',
            index=models.Index(fields=['is_active', 'created_at'], name='matcher_res_is_acti_4ed114_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user', 'is_active'], name='matcher_sav_user_id_c4203f_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['search_type', 'alerts_enabled'], name='matcher_sav_search__a18071_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['alert_frequency', 'last_alert_sent'], name='matcher_sav_alert_f_e4cefa_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['search_type', 'searched_at'], name='matcher_sea_search__802f85_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['user', 'searched_at'], name='matcher_sea_user_id_8e690d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['query', 'search_type'], name='matcher_sea_query_049875_idx'),
        ),
    ]
