# Generated by Django 5.2.4 on 2025-07-29 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0005_conversation_message_popularsearchterms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20)),
                ('template_data', models.JSONField()),
                ('sections', models.JSONField(default=list)),
                ('change_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'matcher_resumetemplateversion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('customized_data', models.JSONField(default=dict, help_text="User's customizations to the base template")),
                ('customized_sections', models.JSONField(default=list, help_text="User's customized sections")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'matcher_userresumetemplate',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='resumetemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='resumetemplate',
            name='matcher_res_is_acti_4ed114_idx',
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='sections',
            field=models.JSONField(default=list, help_text='List of available sections for this template'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='resumetemplate',
            index=models.Index(fields=['is_premium', 'is_active'], name='matcher_res_is_prem_525c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='resumetemplate',
            index=models.Index(fields=['usage_count'], name='matcher_res_usage_c_45d6bb_idx'),
        ),
        migrations.AddField(
            model_name='resumetemplateversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumetemplateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='matcher.resumetemplate'),
        ),
        migrations.AddField(
            model_name='userresumetemplate',
            name='base_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_customizations', to='matcher.resumetemplate'),
        ),
        migrations.AddField(
            model_name='userresumetemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='resumetemplateversion',
            unique_together={('template', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='userresumetemplate',
            unique_together={('user', 'name')},
        ),
    ]
