global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files: []
scrape_configs:
- job_name: hirewise-django
  metrics_path: /api/metrics/
  scrape_interval: 30s
  static_configs:
  - targets:
    - localhost:8000
- job_name: hirewise-celery
  scrape_interval: 30s
  static_configs:
  - targets:
    - localhost:5555
- job_name: redis
  scrape_interval: 30s
  static_configs:
  - targets:
    - localhost:6379
